language: python

python:
- "3.9"

env:
  - VERSION=10.0.1

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - curl -LO https://dist.xebialabs.com/public/xl-cli/$VERSION/linux-amd64/xl
  - chmod +x xl

script:
  - make all